### ISSUE TITLE
Transparent card?

### ISSUE THREAD

**Issue by SdeGeata** [wwalczyszyn/lovelace-light-slider-card#2]
My Home Assistant version: 0.XXX.X

Home Assistant 2022.10.5
Supervisor 2022.10.2
Operating System 9.2
Frontend 20221010.0 - latest

My lovelace configuration method (GUI or yaml):

Both

What I am doing:

Trying to make my light slider card transparent.

What I expected to happen:

Well, a transparent card.

What happened instead:

A non-transparent card.

**Minimal** steps to reproduce:

```yaml
    - entity: light.kitchen
      type: image
      title: Kitchen
      state_image:
        'on': /local/lighting_floorplan/lights/00_transparent_square.png
        'off': /local/lighting_floorplan/lights/00_transparent_square.png
        unavailable: /local/lighting_floorplan/lights/00_unavailable.png
      style:
        top: 71%
        left: 70%
        height: 15%
        width: 8%
        border: 1px dashed rgba(255,0,0,0.0)
      tap_action:
        action: toggle
      double_tap_action:
        action: fire-dom-event
        browser_mod:
          service: browser_mod.popup
          data:
            title: Kitchen
            content:
              type: custom:light-slider-card
              entity: light.kitchen
              transparent_card: true
              icon_position: inside
              slider_color_auto: true
              hide_title: true
              step: 1
      hold_action:
        action: none

# End of code
```

Error messages from the browser console: None

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

![Screen Shot 2022-11-06 at 2 39 28 PM](https://user-images.githubusercontent.com/5808871/200191696-ffd8276a-7b87-4b52-af2d-8836674607e9.png)
